server:
  port: 9099
  
#JDBC Oracle Connection
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: vino
    password: 1234

# MyBatis
mybatis:
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  type-aliases-package: com.bit203.vinoweknow.vo
  type-handlers-package: com.bit203.vinoweknow.dao
      